'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dragonStrap', Object.freeze({
  apiVersion: '2.0.0',
  getCoreState: () => ipcRenderer.invoke('dragonstrap:core-state'),
  getAppInfo: () => ipcRenderer.invoke('dragonstrap:app-info'),
  getReliabilityState: () => ipcRenderer.invoke('dragonstrap:reliability-state'),
  openReliabilityLogs: () => ipcRenderer.invoke('dragonstrap:reliability-open-logs'),
  getUpdateState: () => ipcRenderer.invoke('dragonstrap:updates-state'),
  checkForUpdates: () => ipcRenderer.invoke('dragonstrap:updates-check'),
  openUpdateRelease: () => ipcRenderer.invoke('dragonstrap:updates-open-release'),
  downloadUpdate: () => ipcRenderer.invoke('dragonstrap:updates-download'),
  cancelUpdateDownload: () => ipcRenderer.invoke('dragonstrap:updates-cancel-download'),
  applyUpdate: () => ipcRenderer.invoke('dragonstrap:updates-apply'),
  deferUpdate: hours => ipcRenderer.invoke('dragonstrap:updates-defer', hours),
  clearUpdateDeferral: () => ipcRenderer.invoke('dragonstrap:updates-clear-defer'),
  openUpdateFolder: () => ipcRenderer.invoke('dragonstrap:updates-open-folder'),
  onUpdateDownloadProgress: callback => {
    if (typeof callback !== 'function') return () => {};
    const listener = (_event, progress) => callback(progress);
    ipcRenderer.on('dragonstrap:update-download-progress', listener);
    return () => ipcRenderer.removeListener('dragonstrap:update-download-progress', listener);
  },
  getRobloxStatus: () => ipcRenderer.invoke('dragonstrap:roblox-status'),
  getSettings: () => ipcRenderer.invoke('dragonstrap:settings-get'),
  updateSettings: patch => ipcRenderer.invoke('dragonstrap:settings-update', patch),
  getConfigurationProfiles: () => ipcRenderer.invoke('dragonstrap:configuration-profiles-state'),
  saveConfigurationProfile: name => ipcRenderer.invoke('dragonstrap:configuration-profile-save-current', name),
  cloneConfigurationProfile: (id, name) => ipcRenderer.invoke('dragonstrap:configuration-profile-clone', id, name),
  deleteConfigurationProfile: id => ipcRenderer.invoke('dragonstrap:configuration-profile-delete', id),
  previewConfigurationProfile: id => ipcRenderer.invoke('dragonstrap:configuration-profile-preview', id),
  applyConfigurationProfile: id => ipcRenderer.invoke('dragonstrap:configuration-profile-apply', id),
  exportConfigurationProfile: id => ipcRenderer.invoke('dragonstrap:configuration-profile-export', id),
  importConfigurationProfile: () => ipcRenderer.invoke('dragonstrap:configuration-profile-import'),
  getChannelVersionState: channel => ipcRenderer.invoke('dragonstrap:channel-version-state', channel),
  selectChannel: channel => ipcRenderer.invoke('dragonstrap:channel-version-select', channel),
  openChannelInstallFolder: kind => ipcRenderer.invoke('dragonstrap:channel-open-install-folder', kind),
  getPlayerInstallState: () => ipcRenderer.invoke('dragonstrap:player-install-state'),
  getPlayerInstallPlan: () => ipcRenderer.invoke('dragonstrap:player-install-plan'),
  startPlayerInstall: () => ipcRenderer.invoke('dragonstrap:player-install-start'),
  cancelPlayerInstall: () => ipcRenderer.invoke('dragonstrap:player-install-cancel'),
  onPlayerInstallProgress: callback => {
    if (typeof callback !== 'function') return () => {};
    const listener = (_event, progress) => callback(progress);
    ipcRenderer.on('dragonstrap:player-install-progress', listener);
    return () => ipcRenderer.removeListener('dragonstrap:player-install-progress', listener);
  },
  onRobloxStatusChanged: callback => {
    if (typeof callback !== 'function') return () => {};
    const listener = (_event, status) => callback(status);
    ipcRenderer.on('dragonstrap:roblox-status-changed', listener);
    return () => ipcRenderer.removeListener('dragonstrap:roblox-status-changed', listener);
  },
  launchPlayer: options => ipcRenderer.invoke('dragonstrap:launch-player', options),
  launchStudio: () => ipcRenderer.invoke('dragonstrap:launch-studio'),
  getStudioCenterState: () => ipcRenderer.invoke('dragonstrap:studio-center-state'),
  updateStudioSettings: patch => ipcRenderer.invoke('dragonstrap:studio-settings-update', patch),
  checkStudioChannel: channel => ipcRenderer.invoke('dragonstrap:studio-channel-check', channel),
  selectStudioChannel: channel => ipcRenderer.invoke('dragonstrap:studio-channel-select', channel),
  chooseAndLaunchStudioProject: () => ipcRenderer.invoke('dragonstrap:studio-project-choose-launch'),
  launchRecentStudioProject: id => ipcRenderer.invoke('dragonstrap:studio-project-launch-recent', id),
  backupStudioProject: id => ipcRenderer.invoke('dragonstrap:studio-project-backup', id),
  restoreStudioProjectCopy: (id, backupId) => ipcRenderer.invoke('dragonstrap:studio-project-restore-copy', id, backupId),
  openStudioProjectBackups: id => ipcRenderer.invoke('dragonstrap:studio-project-open-backups', id),
  clearStudioProjectHistory: () => ipcRenderer.invoke('dragonstrap:studio-history-clear'),
  toggleStudioFastFlags: enabled => ipcRenderer.invoke('dragonstrap:studio-fastflags-toggle', enabled),
  setStudioFastFlag: (key, value, type) => ipcRenderer.invoke('dragonstrap:studio-fastflags-set', key, value, type),
  removeStudioFastFlag: key => ipcRenderer.invoke('dragonstrap:studio-fastflags-remove', key),
  restoreStudioFastFlagsBackup: () => ipcRenderer.invoke('dragonstrap:studio-fastflags-restore-backup'),
  openStudioInstallFolder: () => ipcRenderer.invoke('dragonstrap:studio-open-install-folder'),
  openStudioLogsFolder: () => ipcRenderer.invoke('dragonstrap:studio-open-logs-folder'),
  getLaunchHistory: () => ipcRenderer.invoke('dragonstrap:launch-history-get'),
  clearLaunchHistory: () => ipcRenderer.invoke('dragonstrap:launch-history-clear'),
  getPerformanceState: () => ipcRenderer.invoke('dragonstrap:performance-state'),
  applyPerformance: () => ipcRenderer.invoke('dragonstrap:performance-apply'),
  restorePerformance: () => ipcRenderer.invoke('dragonstrap:performance-restore'),
  getPerformanceCenterState: () => ipcRenderer.invoke('dragonstrap:performance-center-state'),
  getPerformanceProfiles: () => ipcRenderer.invoke('dragonstrap:performance-profiles-state'),
  savePerformanceProfile: name => ipcRenderer.invoke('dragonstrap:performance-profile-save', name),
  deletePerformanceProfile: id => ipcRenderer.invoke('dragonstrap:performance-profile-delete', id),
  assignPerformanceExperience: (placeId, profileId) => ipcRenderer.invoke('dragonstrap:performance-experience-assign', placeId, profileId),
  removePerformanceExperience: placeId => ipcRenderer.invoke('dragonstrap:performance-experience-remove', placeId),
  getFastFlagsState: () => ipcRenderer.invoke('dragonstrap:fastflags-state'),
  previewFastFlags: patch => ipcRenderer.invoke('dragonstrap:fastflags-preview', patch),
  getServerIntelligence: (target, options) => ipcRenderer.invoke('dragonstrap:server-intelligence-lookup', target, options),
  clearServerIntelligenceCache: placeId => ipcRenderer.invoke('dragonstrap:server-intelligence-clear-cache', placeId),
  getServerSavedState: placeId => ipcRenderer.invoke('dragonstrap:server-intelligence-saved-state', placeId),
  toggleServerFavorite: (placeId, server) => ipcRenderer.invoke('dragonstrap:server-intelligence-toggle-favorite', placeId, server),
  recordServerJoin: (placeId, server) => ipcRenderer.invoke('dragonstrap:server-intelligence-record-join', placeId, server),
  clearRecentServers: () => ipcRenderer.invoke('dragonstrap:server-intelligence-clear-recent'),
  applyFastFlags: patch => ipcRenderer.invoke('dragonstrap:fastflags-apply', patch),
  restoreFastFlagsBackup: () => ipcRenderer.invoke('dragonstrap:fastflags-restore-backup'),
  exportFastFlags: () => ipcRenderer.invoke('dragonstrap:fastflags-export'),
  importFastFlags: () => ipcRenderer.invoke('dragonstrap:fastflags-import'),
  listFastFlagPresets: () => ipcRenderer.invoke('dragonstrap:fastflags-presets-list'),
  saveFastFlagPreset: name => ipcRenderer.invoke('dragonstrap:fastflags-preset-save', name),
  getFastFlagPreset: id => ipcRenderer.invoke('dragonstrap:fastflags-preset-get', id),
  deleteFastFlagPreset: id => ipcRenderer.invoke('dragonstrap:fastflags-preset-delete', id),
  exportFastFlagPresetShare: id => ipcRenderer.invoke('dragonstrap:fastflags-preset-export-share', id),
  importFastFlagPresetShare: () => ipcRenderer.invoke('dragonstrap:fastflags-preset-import-share'),
  listFastFlagSnapshots: () => ipcRenderer.invoke('dragonstrap:fastflags-snapshots-list'),
  restoreFastFlagSnapshot: id => ipcRenderer.invoke('dragonstrap:fastflags-snapshot-restore', id),
  showFastFlagsFile: () => ipcRenderer.invoke('dragonstrap:fastflags-show-file'),
  getMaintenanceState: () => ipcRenderer.invoke('dragonstrap:maintenance-state'),
  createConfigurationRestorePoint: label => ipcRenderer.invoke('dragonstrap:maintenance-create-restore-point', label),
  restoreConfigurationRestorePoint: id => ipcRenderer.invoke('dragonstrap:maintenance-restore-point', id),
  deleteConfigurationRestorePoint: id => ipcRenderer.invoke('dragonstrap:maintenance-delete-restore-point', id),
  rollbackRobloxPlayer: () => ipcRenderer.invoke('dragonstrap:maintenance-rollback-player'),
  repairUpdateRecovery: () => ipcRenderer.invoke('dragonstrap:maintenance-repair-update-state'),
  runSafeRepair: () => ipcRenderer.invoke('dragonstrap:maintenance-safe-repair'),
  clearMaintenanceCache: scope => ipcRenderer.invoke('dragonstrap:maintenance-clear-cache', scope),
  clearOldRobloxLogs: days => ipcRenderer.invoke('dragonstrap:maintenance-clear-old-logs', days),
  repairClientSettings: () => ipcRenderer.invoke('dragonstrap:maintenance-repair-client-settings'),
  exportDiagnostics: () => ipcRenderer.invoke('dragonstrap:maintenance-export-diagnostics'),
  openMaintenanceLocation: kind => ipcRenderer.invoke('dragonstrap:maintenance-open-location', kind),
  openDataFolder: () => ipcRenderer.invoke('dragonstrap:open-data-folder')
}));
