'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dragonStrap', Object.freeze({
  getAppInfo: () => ipcRenderer.invoke('dragonstrap:app-info'),
  getReliabilityState: () => ipcRenderer.invoke('dragonstrap:reliability-state'),
  openReliabilityLogs: () => ipcRenderer.invoke('dragonstrap:reliability-open-logs'),
  getUpdateState: () => ipcRenderer.invoke('dragonstrap:updates-state'),
  checkForUpdates: () => ipcRenderer.invoke('dragonstrap:updates-check'),
  openUpdateRelease: () => ipcRenderer.invoke('dragonstrap:updates-open-release'),
  getRobloxStatus: () => ipcRenderer.invoke('dragonstrap:roblox-status'),
  getSettings: () => ipcRenderer.invoke('dragonstrap:settings-get'),
  updateSettings: patch => ipcRenderer.invoke('dragonstrap:settings-update', patch),
  getChannelVersionState: channel => ipcRenderer.invoke('dragonstrap:channel-version-state', channel),
  selectChannel: channel => ipcRenderer.invoke('dragonstrap:channel-version-select', channel),
  openChannelInstallFolder: kind => ipcRenderer.invoke('dragonstrap:channel-open-install-folder', kind),
  launchPlayer: options => ipcRenderer.invoke('dragonstrap:launch-player', options),
  launchStudio: () => ipcRenderer.invoke('dragonstrap:launch-studio'),
  getStudioCenterState: () => ipcRenderer.invoke('dragonstrap:studio-center-state'),
  chooseAndLaunchStudioProject: () => ipcRenderer.invoke('dragonstrap:studio-project-choose-launch'),
  launchRecentStudioProject: id => ipcRenderer.invoke('dragonstrap:studio-project-launch-recent', id),
  clearStudioProjectHistory: () => ipcRenderer.invoke('dragonstrap:studio-history-clear'),
  openStudioInstallFolder: () => ipcRenderer.invoke('dragonstrap:studio-open-install-folder'),
  openStudioLogsFolder: () => ipcRenderer.invoke('dragonstrap:studio-open-logs-folder'),
  getLaunchHistory: () => ipcRenderer.invoke('dragonstrap:launch-history-get'),
  clearLaunchHistory: () => ipcRenderer.invoke('dragonstrap:launch-history-clear'),
  getPerformanceState: () => ipcRenderer.invoke('dragonstrap:performance-state'),
  applyPerformance: () => ipcRenderer.invoke('dragonstrap:performance-apply'),
  restorePerformance: () => ipcRenderer.invoke('dragonstrap:performance-restore'),
  getFastFlagsState: () => ipcRenderer.invoke('dragonstrap:fastflags-state'),
  getServerIntelligence: (target, options) => ipcRenderer.invoke('dragonstrap:server-intelligence-lookup', target, options),
  clearServerIntelligenceCache: placeId => ipcRenderer.invoke('dragonstrap:server-intelligence-clear-cache', placeId),
  applyFastFlags: patch => ipcRenderer.invoke('dragonstrap:fastflags-apply', patch),
  restoreFastFlagsBackup: () => ipcRenderer.invoke('dragonstrap:fastflags-restore-backup'),
  exportFastFlags: () => ipcRenderer.invoke('dragonstrap:fastflags-export'),
  importFastFlags: () => ipcRenderer.invoke('dragonstrap:fastflags-import'),
  listFastFlagPresets: () => ipcRenderer.invoke('dragonstrap:fastflags-presets-list'),
  saveFastFlagPreset: name => ipcRenderer.invoke('dragonstrap:fastflags-preset-save', name),
  getFastFlagPreset: id => ipcRenderer.invoke('dragonstrap:fastflags-preset-get', id),
  deleteFastFlagPreset: id => ipcRenderer.invoke('dragonstrap:fastflags-preset-delete', id),
  showFastFlagsFile: () => ipcRenderer.invoke('dragonstrap:fastflags-show-file'),
  getMaintenanceState: () => ipcRenderer.invoke('dragonstrap:maintenance-state'),
  clearMaintenanceCache: scope => ipcRenderer.invoke('dragonstrap:maintenance-clear-cache', scope),
  clearOldRobloxLogs: days => ipcRenderer.invoke('dragonstrap:maintenance-clear-old-logs', days),
  repairClientSettings: () => ipcRenderer.invoke('dragonstrap:maintenance-repair-client-settings'),
  exportDiagnostics: () => ipcRenderer.invoke('dragonstrap:maintenance-export-diagnostics'),
  openMaintenanceLocation: kind => ipcRenderer.invoke('dragonstrap:maintenance-open-location', kind),
  openDataFolder: () => ipcRenderer.invoke('dragonstrap:open-data-folder')
}));
